[project]
name = "eegqc"
version = "0.1.0"
description = "QC toolkit for EEG data"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.8",
    "mne>=1.11.0",
    "mne-lsl>=1.12.0",
]


